DROP TABLE IF EXISTS TEAMS;

CREATE TABLE TEAMS(
  ID_TEAM INTEGER PRIMARY KEY NOT NULL,
  NAME_CATEGORY_PL VARCHAR(64) NOT NULL,
  NAME_CATEGORY_ENG VARCHAR(64) NOT NULL
);

CREATE TABLE PLAYERS(
  ID_PLAYER INTEGER PRIMARY KEY NOT NULL,
  NAME_PLAYER varchar(64) NOT NULL,
  SURNAME varchar(64) NOT NULL,
  NUMBER INTEGER,
  POSITION VARCHAR(64) NOT NULL,
  DATE_OF_BIRTH DATE NOT NULL
);

CREATE TABLE PLAYERS_TEAM(
    ID INTEGER PRIMARY KEY NOT NULL,
    ID_PLAYER INTEGER NOT NULL,
    ID_TEAM INTEGER NOT NULL
)
